import { Academy, Instructor, Student, Lead, ClassSchedule, PaymentHistory, Technique, GraduationCandidate, MarketingCampaign, AcademyPost } from "./types";

export const initialInstructors: Instructor[] = [
  {
    id: "inst-1",
    academyId: "ac-2",
    name: "Messias Batista",
    email: "messiasbjunior76@gmail.com",
    phone: "+55 (11) 98111-2233",
    belt: "Black",
    birthDate: "1975-07-21", // Birthday is Today (July 21)
    status: "Active",
  },
  {
    id: "inst-2",
    academyId: "ac-1",
    name: "Prof. André",
    email: "andre@bjjacademy.com",
    phone: "+55 (21) 97766-5544",
    belt: "Black",
    birthDate: "1983-07-28", // Birthday is Next Week (July 28)
    status: "Active",
  },
  {
    id: "inst-3",
    academyId: "ac-2",
    name: "Professora Flávia",
    email: "flavia@bjjacademy.com",
    phone: "+55 (11) 95555-1234",
    belt: "Purple",
    birthDate: "1990-09-12",
    status: "Active",
  },
  {
    id: "inst-4",
    academyId: "ac-3",
    name: "Mestre Renzo",
    email: "renzo@bjjacademy.com",
    phone: "+1 (619) 555-0100",
    belt: "Black",
    birthDate: "1972-07-22", // Birthday is Tomorrow (July 22)
    status: "Active",
  },
  {
    id: "inst-5",
    academyId: "ac-4",
    name: "Prof. Roberto Mendes",
    email: "roberto@layoutjiujitsu.com.br",
    phone: "+55 (11) 97123-9988",
    belt: "Black",
    birthDate: "1985-04-18",
    status: "Active",
  }
];

export const initialAcademies: Academy[] = [
  {
    id: "ac-1",
    name: "Gracie Barra Barra da Tijuca",
    unit: "Matriz - Rio de Janeiro",
    activeStudents: 145,
    monthlyRevenue: 18200,
    pendingGraduations: 12,
    instructorsCount: 5,
    subdomain: "graciebarra",
    customDomain: "gracie.bjjacademy.app.br",
    asaasWalletId: "wal_gracie_991823901",
    splitRatePercentage: 95
  },
  {
    id: "ac-2",
    name: "Alliance São Paulo",
    unit: "São Paulo - Itaim Bibi",
    activeStudents: 112,
    monthlyRevenue: 15400,
    pendingGraduations: 8,
    instructorsCount: 4,
    subdomain: "alliance",
    customDomain: "alliance.bjjacademy.app.br",
    asaasWalletId: "wal_alliance_551829001",
    splitRatePercentage: 95
  },
  {
    id: "ac-3",
    name: "Atos BJJ San Diego",
    unit: "California - Headquarters",
    activeStudents: 89,
    monthlyRevenue: 13500,
    pendingGraduations: 15,
    instructorsCount: 3,
    subdomain: "atos",
    customDomain: "atos.bjjacademy.app.br",
    asaasWalletId: "wal_atos_883921094",
    splitRatePercentage: 95
  },
  {
    id: "ac-4",
    name: "Loyalty Jiu-Jitsu",
    unit: "Matriz - São Paulo",
    activeStudents: 128,
    monthlyRevenue: 19800,
    pendingGraduations: 14,
    instructorsCount: 4,
    subdomain: "loyalty",
    customDomain: "loyalty.bjjacademy.app.br",
    asaasWalletId: "wal_loyalty_772910482",
    splitRatePercentage: 95,
    logoUrl: "/loyalty_logo.jpg"
  }
];

export const initialStudents: Student[] = [
  {
    id: "st-1",
    academyId: "ac-2",
    name: "Guilherme Silva",
    email: "guilherme.silva@email.com",
    phone: "+55 (11) 98765-4321",
    cpf: "123.456.789-01",
    plan: "Mensal",
    planValue: 220,
    belt: "White",
    stripes: 2,
    attendance30Days: 4,
    daysSinceLastClass: 14,
    status: "ChurnRisk",
    paymentStatus: "Overdue",
    registrationDate: "2025-01-15",
    birthDate: "1995-05-12",
    asaasCustomerId: "cus_0000010091",
    asaasSubscriptionId: "sub_10091823",
    billingType: "BOLETO",
    loyaltyPoints: 350,
    loyaltyTier: "Bronze",
    referralCode: "GUILHERME350",
    badges: ["Primeiro Graal", "Checkin Starter"]
  },
  {
    id: "st-2",
    academyId: "ac-1",
    name: "Beatriz Oliveira",
    email: "beatriz.oliveira@email.com",
    phone: "+55 (21) 99123-4567",
    cpf: "234.567.890-12",
    plan: "Anual",
    planValue: 180,
    belt: "Blue",
    stripes: 4,
    attendance30Days: 16,
    daysSinceLastClass: 1,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2023-11-10",
    birthDate: "1998-07-21",
    asaasCustomerId: "cus_0000010092",
    asaasSubscriptionId: "sub_10091824",
    billingType: "CREDIT_CARD",
    loyaltyPoints: 2450,
    loyaltyTier: "Ouro",
    referralCode: "BEATRIZ245",
    badges: ["Cascagrossa 20 Treinos", "Samurai 6 Meses", "4º Graal Azul"]
  },
  {
    id: "st-3",
    academyId: "ac-2",
    name: "Carlos Eduardo",
    email: "carlos.edu@email.com",
    phone: "+55 (11) 97766-5544",
    cpf: "345.678.901-23",
    plan: "Semestral",
    planValue: 200,
    belt: "Purple",
    stripes: 1,
    attendance30Days: 12,
    daysSinceLastClass: 3,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2021-04-05",
    birthDate: "1990-02-14",
    asaasCustomerId: "cus_0000010093",
    asaasSubscriptionId: "sub_10091825",
    billingType: "PIX",
    loyaltyPoints: 1800,
    loyaltyTier: "Prata",
    referralCode: "CARLOS180",
    badges: ["Guardião Passagem", "3 Anos de Tatame"]
  },
  {
    id: "st-4",
    academyId: "ac-2",
    name: "Lucas Alencar",
    email: "lucas.alencar@email.com",
    phone: "+55 (11) 91234-5678",
    cpf: "456.789.012-34",
    plan: "Mensal",
    planValue: 220,
    belt: "White",
    stripes: 0,
    attendance30Days: 2,
    daysSinceLastClass: 21,
    status: "ChurnRisk",
    paymentStatus: "Overdue",
    registrationDate: "2026-03-01",
    birthDate: "2012-07-30",
    guardianName: "Renata Alencar (Mãe)",
    asaasCustomerId: "cus_0000010094",
    asaasSubscriptionId: "sub_10091826",
    billingType: "BOLETO"
  },
  {
    id: "st-5",
    academyId: "ac-3",
    name: "Ricardo 'Trator' Souza",
    email: "ricardo.trator@email.com",
    phone: "+1 (619) 555-0199",
    cpf: "567.890.123-45",
    plan: "Anual",
    planValue: 250,
    belt: "Brown",
    stripes: 3,
    attendance30Days: 22,
    daysSinceLastClass: 0,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2018-06-20",
    birthDate: "1988-11-05",
    asaasCustomerId: "cus_0000010095",
    asaasSubscriptionId: "sub_10091827",
    billingType: "PIX"
  },
  {
    id: "st-6",
    academyId: "ac-1",
    name: "Mariana Costa",
    email: "mariana.costa@email.com",
    phone: "+55 (21) 98111-2233",
    cpf: "678.901.234-56",
    plan: "Trimestral",
    planValue: 210,
    belt: "Blue",
    stripes: 2,
    attendance30Days: 8,
    daysSinceLastClass: 8,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2024-05-18",
    birthDate: "1993-03-27",
    asaasCustomerId: "cus_0000010096",
    asaasSubscriptionId: "sub_10091828",
    billingType: "CREDIT_CARD"
  },
  {
    id: "st-7",
    academyId: "ac-4",
    name: "Felipe Ramos (Layout BJJ)",
    email: "felipe.ramos@layoutjiujitsu.com.br",
    phone: "+55 (11) 98844-3322",
    cpf: "789.012.345-67",
    plan: "Mensal",
    planValue: 220,
    belt: "Purple",
    stripes: 2,
    attendance30Days: 16,
    daysSinceLastClass: 1,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2023-02-10",
    birthDate: "1992-08-14",
    asaasCustomerId: "cus_0000010097",
    asaasSubscriptionId: "sub_10091829",
    billingType: "PIX",
    loyaltyPoints: 1950,
    loyaltyTier: "Prata",
    referralCode: "FELIPELAYOUT",
    badges: ["Competidor Ativo", "Finalizador"]
  },
  {
    id: "st-8",
    academyId: "ac-4",
    name: "Amanda Silveira (Layout BJJ)",
    email: "amanda.silveira@layoutjiujitsu.com.br",
    phone: "+55 (11) 97711-2200",
    cpf: "890.123.456-78",
    plan: "Anual",
    planValue: 200,
    belt: "Blue",
    stripes: 3,
    attendance30Days: 14,
    daysSinceLastClass: 2,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2024-01-20",
    birthDate: "1996-11-03",
    asaasCustomerId: "cus_0000010098",
    asaasSubscriptionId: "sub_10091830",
    billingType: "CREDIT_CARD",
    loyaltyPoints: 1200,
    loyaltyTier: "Bronze",
    referralCode: "AMANDALAYOUT",
    badges: ["Guerreira do Tatame", "Top Frequência"]
  },
  {
    id: "st-9",
    academyId: "ac-2",
    name: "Felipe Mendes",
    email: "felipe.mendes@email.com",
    phone: "+55 (11) 99988-7766",
    cpf: "789.012.345-67",
    plan: "Mensal",
    planValue: 220,
    belt: "White",
    stripes: 3,
    attendance30Days: 14,
    daysSinceLastClass: 2,
    status: "Active",
    paymentStatus: "Paid",
    registrationDate: "2025-08-12",
    birthDate: "2001-12-10",
    asaasCustomerId: "cus_0000010097",
    asaasSubscriptionId: "sub_10091829",
    billingType: "PIX"
  },
];

export const initialLeads: Lead[] = [
  {
    id: "ld-1",
    academyId: "ac-2",
    name: "Rodrigo Almeida",
    email: "rodrigo.almeida@gmail.com",
    phone: "+55 (11) 96321-7890",
    phase: "Capture",
    notes: "Interessado no plano Pro. Praticava Judô na infância.",
    dateCreated: "2026-07-05",
  },
  {
    id: "ld-2",
    academyId: "ac-2",
    name: "Patrícia Lima",
    email: "patricia.lima@hotmail.com",
    phone: "+55 (11) 95555-1234",
    phase: "Trial Scheduled",
    notes: "Aula experimental agendada para sábado às 10:00 com Prof. André.",
    dateCreated: "2026-07-06",
  },
  {
    id: "ld-3",
    academyId: "ac-1",
    name: "Gabriel Santos",
    email: "gabriel.santos@outlook.com",
    phone: "+55 (21) 94444-5555",
    phase: "Trial Attended",
    notes: "Gostou muito do treino. Pediu detalhes da taxa de matrícula e kimono.",
    dateCreated: "2026-07-04",
  },
  {
    id: "ld-4",
    academyId: "ac-2",
    name: "Amanda Guedes",
    email: "amanda.guedes@gmail.com",
    phone: "+55 (11) 98888-2222",
    phase: "Proposal",
    notes: "Enviado proposta anual com desconto de 15% no Pix.",
    dateCreated: "2026-07-02",
  },
  {
    id: "ld-5",
    academyId: "ac-2",
    name: "Jeferson Melo",
    email: "jeferson.melo@gmail.com",
    phone: "+55 (11) 91111-9999",
    phase: "Won",
    notes: "Inscrito no plano Basic. Comprou kimono oficial.",
    dateCreated: "2026-06-28",
  },
];

export const initialClassSchedules: ClassSchedule[] = [
  {
    id: "cl-1",
    academyId: "ac-2",
    className: "Fundamentos Iniciante (Gi)",
    instructorName: "Mestre Marcelo",
    time: "07:00 - 08:00",
    daysOfWeek: ["Segunda", "Quarta", "Sexta"],
    activeCount: 18,
  },
  {
    id: "cl-2",
    academyId: "ac-2",
    className: "Jiu-Jitsu Avançado (Gi)",
    instructorName: "Prof. André",
    time: "12:00 - 13:30",
    daysOfWeek: ["Segunda", "Terça", "Quarta", "Quinta"],
    activeCount: 24,
  },
  {
    id: "cl-3",
    academyId: "ac-1",
    className: "No-Gi Noite (Submission)",
    instructorName: "Prof. André",
    time: "19:00 - 20:30",
    daysOfWeek: ["Terça", "Quinta"],
    activeCount: 16,
  },
  {
    id: "cl-4",
    academyId: "ac-2",
    className: "Kids BJJ (6-12 anos)",
    instructorName: "Professora Flávia",
    time: "17:30 - 18:30",
    daysOfWeek: ["Segunda", "Quarta"],
    activeCount: 12,
  },
];

export const initialPayments: PaymentHistory[] = [
  {
    id: "pay-1",
    academyId: "ac-1",
    studentId: "st-2",
    studentName: "Beatriz Oliveira",
    amount: 220,
    date: "2026-07-01",
    status: "Paid",
    method: "PIX",
  },
  {
    id: "pay-2",
    academyId: "ac-2",
    studentId: "st-3",
    studentName: "Carlos Eduardo",
    amount: 220,
    date: "2026-07-02",
    status: "Paid",
    method: "CREDIT_CARD",
  },
  {
    id: "pay-3",
    academyId: "ac-3",
    studentId: "st-5",
    studentName: "Ricardo 'Trator' Souza",
    amount: 250,
    date: "2026-07-03",
    status: "Paid",
    method: "PIX",
  },
  {
    id: "pay-4",
    academyId: "ac-2",
    studentId: "st-1",
    studentName: "Guilherme Silva",
    amount: 220,
    date: "2026-06-15",
    status: "Failed",
    method: "BOLETO",
  },
  {
    id: "pay-5",
    academyId: "ac-1",
    studentId: "st-6",
    studentName: "Mariana Costa",
    amount: 220,
    date: "2026-07-05",
    status: "Paid",
    method: "CREDIT_CARD",
  },
];

export const initialTechniques: Technique[] = [
  {
    id: "tech-1",
    name: "Scissors Sweep (Raspagem de Tesoura)",
    category: "Guard Retention",
    difficulty: "Beginner",
    description: "Traditional open guard sweep using collar-and-sleeve grip, pulling partner over knee shield and scissoring legs to gain mount.",
  },
  {
    id: "tech-2",
    name: "Knee Slide Pass (Passagem de Knee Slide)",
    category: "Guard Passing",
    difficulty: "Intermediate",
    description: "Core pressure pass slicing one knee over target's leg from half guard with underhook control to secure side mount.",
  },
  {
    id: "tech-3",
    name: "Kimura Lock from Closed Guard",
    category: "Submissions",
    difficulty: "Beginner",
    description: "Classic wrist and elbow joint lock applied by sitting up to trap the partner's arm, rotating the hand behind the back.",
  },
  {
    id: "tech-4",
    name: "Granby Roll Guard Recovery",
    category: "Guard Retention",
    difficulty: "Advanced",
    description: "Inverted roll across the shoulders to re-establish knee-to-elbow connection when opponent tries to run around the guard.",
  },
  {
    id: "tech-5",
    name: "Single Leg Takedown (Catada de Perna)",
    category: "Takedowns",
    difficulty: "Intermediate",
    description: "Wrestling-based entry attacking the near leg, using posture and head pressure inside the ribs to sweep or spin the partner down.",
  },
];

export const initialGraduations: GraduationCandidate[] = [
  {
    id: "cand-1",
    academyId: "ac-1",
    studentName: "Beatriz Oliveira",
    currentBelt: "Blue",
    currentStripes: 4,
    attendanceCount: 164,
    monthsInCurrentBelt: 24,
    status: "Eligible",
  },
  {
    id: "cand-2",
    academyId: "ac-2",
    studentName: "Felipe Mendes",
    currentBelt: "White",
    currentStripes: 3,
    attendanceCount: 68,
    monthsInCurrentBelt: 8,
    status: "Pending Exam",
  },
  {
    id: "cand-3",
    academyId: "ac-1",
    studentName: "Mariana Costa",
    currentBelt: "Blue",
    currentStripes: 2,
    attendanceCount: 92,
    monthsInCurrentBelt: 14,
    status: "Eligible",
  },
];

export const initialCampaigns: MarketingCampaign[] = [
  {
    id: "cmp-1",
    academyId: "ac-2",
    name: "Ausentes do Tatame (Reengajamento)",
    type: "WhatsApp",
    status: "Running",
    sentCount: 24,
    targetAudience: "Alunos inativos há mais de 10 dias",
  },
  {
    id: "cmp-2",
    academyId: "ac-1",
    name: "Boas-Vindas & Onboarding de Novos Alunos",
    type: "Email",
    status: "Completed",
    sentCount: 156,
    openRate: 84.5,
    clickRate: 31.2,
    targetAudience: "Novos matriculados nos últimos 3 meses",
  },
  {
    id: "cmp-3",
    academyId: "ac-2",
    name: "Promoção de Inverno Kimono Grátis",
    type: "WhatsApp",
    status: "Draft",
    sentCount: 0,
    targetAudience: "Leads do funil na fase de proposta",
  },
];

export const initialAcademyPosts: AcademyPost[] = [
  {
    id: "post-1",
    academyId: "ac-4",
    academyName: "Layout Jiu-Jitsu",
    authorName: "Prof. Roberto Mendes",
    authorRole: "Professor",
    title: "🏆 Copa Layout Jiu-Jitsu & Open BJJ Championship 2026",
    category: "Campeonato",
    description: "Estão abertas as inscrições oficiais para a Copa Layout Jiu-Jitsu! O torneio contará com disputas com e sem kimono (Gi e No-Gi) do Pré-Mirim ao Master, premiação em dinheiro para os absolutos de Faixa Azul a Preta, medalhas exclusivas e troféu por equipes.",
    flyerImageUrl: "/src/assets/images/bjj_championship_flyer_1787353673856.jpg",
    eventDate: "2026-10-15",
    eventTime: "08:30 às 18:00",
    location: "Ginásio Poliesportivo Central - São Paulo/SP",
    registrationFee: 120,
    registrationDeadline: "2026-10-10",
    externalRegistrationUrl: "https://soucompetidor.com.br/evento/copa-layout-bjj-2026",
    targetAudience: "Todos os Alunos",
    pinned: true,
    createdAt: "2026-08-20T10:00:00.000Z",
    interestedStudentIds: ["st-1", "st-2", "st-3"],
    viewsCount: 142
  },
  {
    id: "post-2",
    academyId: "ac-4",
    academyName: "Layout Jiu-Jitsu",
    authorName: "Prof. Roberto Mendes",
    authorRole: "Professor",
    title: "🥋 Seminário Técnico Especial: Passagem de Guarda Moderna & Berimbolo",
    category: "Seminário",
    description: "Seminário intensivo de 4 horas focando nos detalhes de retenção de guarda, passagem emborcada e transições para as costas. Aberto para todas as faixas da academia. Vagas limitadas por capacidade do tatame.",
    flyerImageUrl: "/src/assets/images/bjj_seminar_flyer_1787353688432.jpg",
    eventDate: "2026-11-28",
    eventTime: "14:00 às 18:00",
    location: "Tatame Principal - Layout Jiu-Jitsu Matriz",
    registrationFee: 80,
    registrationDeadline: "2026-11-25",
    externalRegistrationUrl: "https://layoutjiujitsu.com.br/seminario",
    targetAudience: "Todos os Alunos",
    pinned: false,
    createdAt: "2026-08-18T14:30:00.000Z",
    interestedStudentIds: ["st-2"],
    viewsCount: 88
  },
  {
    id: "post-3",
    academyId: "ac-2",
    academyName: "Alliance São Paulo",
    authorName: "Mestre Marcelo",
    authorRole: "Mestre",
    title: "🎓 Grande Cerimônia de Graduação & Entrega de Faixas 2026.2",
    category: "Graduação",
    description: "Convocamos todos os alunos para a tradicional graduação de fim de ano. Teremos o treinão geral comemorativo, entrega de graus para quem atingiu o volume de aulas exigido e batismo das novas faixas.",
    flyerImageUrl: "/src/assets/images/bjj_seminar_flyer_1787353688432.jpg",
    eventDate: "2026-12-19",
    eventTime: "10:00",
    location: "Dojo Central Alliance - São Paulo",
    registrationFee: 0,
    registrationDeadline: "2026-12-15",
    targetAudience: "Todos os Alunos",
    pinned: true,
    createdAt: "2026-08-15T09:00:00.000Z",
    interestedStudentIds: ["st-1", "st-4"],
    viewsCount: 210
  }
];

export const initialLoyaltyRewards = [
  {
    id: "rew-1",
    title: "Desconto de 20% na Próxima Mensalidade",
    description: "Abatimento automático na sua próxima fatura Asaas via BJJ Loyalty.",
    pointsCost: 1000,
    category: "Desconto",
    stock: 99,
    iconName: "Percent"
  },
  {
    id: "rew-2",
    title: "Patch Oficial BJJ Academy para Kimono",
    description: "Patch bordado de alta densidade da academia contratante.",
    pointsCost: 500,
    category: "Equipamento",
    stock: 25,
    iconName: "Award"
  },
  {
    id: "rew-3",
    title: "Inscrição Grátis em Seminário Técnico",
    description: "Passe VIP para o próximo seminário de passagem de guarda e raspagens.",
    pointsCost: 1500,
    category: "Experiência",
    stock: 10,
    iconName: "Sparkles"
  },
  {
    id: "rew-4",
    title: "Kimono Trançado Especial da Academia",
    description: "Kimono trançado leve aprovado para treinos e competições.",
    pointsCost: 3500,
    category: "Equipamento",
    stock: 5,
    iconName: "Shield"
  },
  {
    id: "rew-5",
    title: "Exame de Graduação Gratuito",
    description: "Isenção da taxa do exame de faixa e diploma de graduação.",
    pointsCost: 2000,
    category: "Graduação",
    stock: 50,
    iconName: "GraduationCap"
  }
];
